### ISSUE TITLE
logicalType is not supported

### ISSUE THREAD

**Issue by amihaygil** [leocalm/avro_validator#29]
schema = json.dumps({
    'name': 'test schema',
    'type': 'record',
    'doc': 'schema for testing avro_validator',
    'fields': [
                            {
                        "name": "event_time",
                        "type": "long",
                        "logicalType": "timestamp-millis"
                    }
    ]
})

schema = Schema(schema)
parsed_schema = schema.parse()

get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amihayg/.virtualenvs/data-entity-schema/lib/python3.9/site-packages/avro_validator/schema.py", line 28, in parse
    return RecordType.build(schema, skip_extra_keys=skip_extra_keys)
  File "/Users/amihayg/.virtualenvs/data-entity-schema/lib/python3.9/site-packages/avro_validator/avro_types.py", line 673, in build
    record_type.__fields = {
  File "/Users/amihayg/.virtualenvs/data-entity-schema/lib/python3.9/site-packages/avro_validator/avro_types.py", line 674, in <dictcomp>
    field['name']: RecordTypeField.build(
  File "/Users/amihayg/.virtualenvs/data-entity-schema/lib/python3.9/site-packages/avro_validator/avro_types.py", line 440, in build
    cls._validate_json_repr(json_repr, skip_extra_keys=skip_extra_keys)
  File "/Users/amihayg/.virtualenvs/data-entity-schema/lib/python3.9/site-packages/avro_validator/avro_types.py", line 72, in _validate_json_repr
    raise ValueError(f'The {cls.__name__} can only contains '
ValueError: The RecordTypeField can only contains {'doc', 'default', 'name', 'order', 'aliases', 'type'} keys, but does contain also {'logicalType'}

**Comment by amihaygil** [comment]
it is supported accroding to spec https://avro.apache.org/docs/1.8.0/spec.html#Logical+Types

**Comment by lipowskm** [comment]
+1, I get the same when trying to parse Decimal type:

`ValueError: Error parsing the field [test]: The FixedType can only contains {'namespace', 'aliases', 'name', 'type', 'size'} keys, but does contain also {'scale', 'logicalType', 'precision'}`

**Comment by manmat** [comment]
@amihaygil I don't think what you are trying to validate is actually a valid schema. Consider the following:
```
{
    "type": "record",
    "name": "timestampExample",
    "fields": [
        {
            "name": "timestamp",
            "type": {
                "type": "long",
                "logicalType": "timestamp-millis"
        }
    ]
}
```
A complex type has to be an object with a `type` and a `logicalType` field.
